@echo off
setlocal EnableDelayedExpansion
title NEXORA - Environment / API Key Setup

REM ============================================================
REM  NEXORA - Interactive API key provisioning
REM  Writes secrets to .env.local (git-ignored, server-side only)
REM  Safe to re-run: existing values are kept unless you overwrite.
REM ============================================================

color 0B
echo.
echo  ==========================================================
echo    N E X O R A   -   Environment Setup
echo  ==========================================================
echo.
echo  This will create or update .env.local with your API keys.
echo  Press ENTER at any prompt to keep the current value.
echo.

set "ENVFILE=.env.local"
set "EXAMPLE=.env.example"

REM ---- Guard: run from the project root -----------------------
if not exist "package.json" (
  color 0C
  echo  [ERROR] package.json not found.
  echo  Run this script from the project root folder.
  echo.
  pause
  exit /b 1
)

REM ---- Back up an existing env file ---------------------------
if exist "%ENVFILE%" (
  echo  Existing %ENVFILE% found - creating backup...
  copy /y "%ENVFILE%" "%ENVFILE%.bak" >nul
  echo  Backup saved to %ENVFILE%.bak
  echo.
)

REM ---- Load existing values so re-runs are non-destructive -----
call :loadExisting

echo  ----------------------------------------------------------
echo   PAYMOB  (card + local payment methods)
echo  ----------------------------------------------------------
call :ask PAYMOB_API_KEY          "Paymob API key"
call :ask PAYMOB_INTEGRATION_ID   "Paymob integration ID (card)"
call :ask PAYMOB_IFRAME_ID        "Paymob iframe ID"
call :ask PAYMOB_HMAC_SECRET      "Paymob HMAC secret (webhook verification)"
echo.

echo  ----------------------------------------------------------
echo   VODAFONE CASH  (wallet)
echo  ----------------------------------------------------------
call :ask VODAFONE_CASH_MERCHANT_ID "Vodafone Cash merchant ID"
call :ask VODAFONE_CASH_API_KEY     "Vodafone Cash API key"
call :ask VODAFONE_CASH_WALLET_INTEGRATION_ID "Paymob wallet integration ID"
echo.

echo  ----------------------------------------------------------
echo   DATABASE  and  SESSIONS
echo  ----------------------------------------------------------
call :ask DATABASE_URL   "PostgreSQL URL (postgres://user:pass@host:5432/nexora)"
call :ask SESSION_SECRET "Session secret (leave blank to auto-generate)"
echo.

echo  ----------------------------------------------------------
echo   OPTIONAL INTEGRATIONS
echo  ----------------------------------------------------------
call :ask SMTP_HOST         "SMTP host (email delivery)"
call :ask SMTP_USER         "SMTP username"
call :ask SMTP_PASS         "SMTP password"
call :ask WHATSAPP_API_TOKEN "WhatsApp Business API token"
call :ask OPENAI_API_KEY    "OpenAI / AI provider key"
call :ask S3_BUCKET         "Object storage bucket name"
call :ask S3_ACCESS_KEY     "Object storage access key"
call :ask S3_SECRET_KEY     "Object storage secret key"
echo.

REM ---- Auto-generate a session secret if still empty -----------
if "!SESSION_SECRET!"=="" (
  echo  Generating a random SESSION_SECRET...
  for /f "delims=" %%G in ('powershell -NoProfile -Command "[Convert]::ToBase64String((1..48 ^| ForEach-Object {Get-Random -Max 256}))" 2^>nul') do set "SESSION_SECRET=%%G"
  if "!SESSION_SECRET!"=="" set "SESSION_SECRET=CHANGE_ME_INSECURE_FALLBACK"
)

REM ---- Write the file -----------------------------------------
echo  Writing %ENVFILE% ...
(
  echo # ============================================================
  echo # NEXORA environment - GENERATED BY setup-env.bat
  echo # Generated: %DATE% %TIME%
  echo #
  echo # SERVER-SIDE ONLY. Never expose these to the browser and
  echo # never commit this file to version control.
  echo # ============================================================
  echo.
  echo # ---------- Paymob ----------
  echo PAYMOB_API_KEY=!PAYMOB_API_KEY!
  echo PAYMOB_INTEGRATION_ID=!PAYMOB_INTEGRATION_ID!
  echo PAYMOB_IFRAME_ID=!PAYMOB_IFRAME_ID!
  echo PAYMOB_HMAC_SECRET=!PAYMOB_HMAC_SECRET!
  echo.
  echo # ---------- Vodafone Cash ----------
  echo VODAFONE_CASH_MERCHANT_ID=!VODAFONE_CASH_MERCHANT_ID!
  echo VODAFONE_CASH_API_KEY=!VODAFONE_CASH_API_KEY!
  echo VODAFONE_CASH_WALLET_INTEGRATION_ID=!VODAFONE_CASH_WALLET_INTEGRATION_ID!
  echo.
  echo # ---------- Core ----------
  echo DATABASE_URL=!DATABASE_URL!
  echo SESSION_SECRET=!SESSION_SECRET!
  echo.
  echo # ---------- Email ----------
  echo SMTP_HOST=!SMTP_HOST!
  echo SMTP_USER=!SMTP_USER!
  echo SMTP_PASS=!SMTP_PASS!
  echo.
  echo # ---------- Integrations ----------
  echo WHATSAPP_API_TOKEN=!WHATSAPP_API_TOKEN!
  echo OPENAI_API_KEY=!OPENAI_API_KEY!
  echo S3_BUCKET=!S3_BUCKET!
  echo S3_ACCESS_KEY=!S3_ACCESS_KEY!
  echo S3_SECRET_KEY=!S3_SECRET_KEY!
) > "%ENVFILE%"

REM ---- Ensure .gitignore covers it ------------------------------
findstr /x /c:".env.local" .gitignore >nul 2>&1
if errorlevel 1 (
  echo.>> .gitignore
  echo .env.local>> .gitignore
  echo .env.local.bak>> .gitignore
  echo  Added .env.local to .gitignore
)

REM ---- Report which keys are still missing ----------------------
echo.
echo  ==========================================================
echo    Summary
echo  ==========================================================
set "MISSING=0"
call :check PAYMOB_API_KEY
call :check PAYMOB_INTEGRATION_ID
call :check PAYMOB_HMAC_SECRET
call :check DATABASE_URL
call :check SESSION_SECRET

echo.
if !MISSING! GTR 0 (
  color 0E
  echo  [WARNING] !MISSING! required key^(s^) are still empty.
  echo  Payments or the database will not work until they are set.
  echo  Re-run this script at any time to fill them in.
) else (
  color 0A
  echo  [OK] All required keys are present.
)

echo.
echo  File written: %ENVFILE%
echo  This file is git-ignored and must never reach the browser.
echo.
pause
exit /b 0

REM ============================================================
REM  Subroutines
REM ============================================================

:ask
REM %1 = variable name, %2 = human-readable prompt
setlocal
set "VAR=%~1"
endlocal & set "VAR=%~1"
call set "CURRENT=%%!VAR!%%"
if defined CURRENT (
  if not "!CURRENT!"=="" (
    echo    !VAR! is already set. Press ENTER to keep it.
  )
)
set /p "INPUT=   %~2: "
if not "!INPUT!"=="" set "!VAR!=!INPUT!"
goto :eof

:check
REM Warn if a required variable is empty
call set "VAL=%%%~1%%"
if "!VAL!"=="" (
  echo    [MISSING] %~1
  set /a MISSING+=1
) else (
  echo    [  OK   ] %~1
)
goto :eof

:loadExisting
REM Re-read previously saved values so ENTER keeps them
if not exist "%ENVFILE%" goto :eof
for /f "usebackq tokens=1,* delims==" %%A in ("%ENVFILE%") do (
  set "LINE=%%A"
  if not "!LINE:~0,1!"=="#" (
    if not "%%A"=="" set "%%A=%%B"
  )
)
goto :eof
